import "./globals.css";
import Sidebar from "./components/Sidebar";

import { personalData } from "../data/page-data";

export const metadata = {
  title: "Resume Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Sidebar data={personalData} />
        {children}
      </body>
    </html>
  );
}
