import "./globals.css";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Resume Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Sidebar />
      <body>{children}</body>
    </html>
  );
}
